Artifact Object Number Pad UI
wakralabconsulting/qmapp pull request #38
Opened 2018-08-20 18:44 UTC by anjusr

Artifact Object Number Pad UI

2018-08-20 23:18 UTC, jageet requested changes

2018-08-21 05:42 UTC, anjusr commented on QatarMuseum/ViewController/FloorMapViewController.swift
> +        } else if(level == levelNumber.three) {
its not mine.. this i edited to remove conflict

2018-08-21 05:43 UTC, anjusr commented on QatarMuseum/ar.lproj/Localizable.strings
> +"OBJECT_INFO" = "next to         to view the details";
to place tat image in btw

2018-08-21 05:56 UTC, jageet commented on QatarMuseum/ViewController/FloorMapViewController.swift
> +        } else if(level == levelNumber.three) {
Remove this. This is redundant.

2018-08-21 05:57 UTC, jageet commented on QatarMuseum/ar.lproj/Localizable.strings
> +"OBJECT_INFO" = "next to         to view the details";
Ok fine. Will this be constant in all the devices?

2018-08-21 06:12 UTC, anjusr commented on QatarMuseum/ar.lproj/Localizable.strings
> +"OBJECT_INFO" = "next to         to view the details";
yup

2018-08-21 06:16 UTC, anjusr commented on QatarMuseum/ViewController/FloorMapViewController.swift
> +        } else if(level == levelNumber.three) {
wat to remove here

2018-08-21 06:48 UTC, merged